### PR TITLE
Adding Test4 to Testing Branch

### PR DESCRIPTION
**Pull request by Ram-Chennale**
Hi SDET,

please check Test4 block  of code in TestingBranch

Thanks
Tester

### CODE REVIEW

**Comment by RamChennale** [comment]
Hey Tester,

looks pretty good, please add condition to verify User can able to VOTE.

Regards
SDET

**Comment by Ram-Chennale** [comment]
Okay, will do that.

**Comment by Ram-Chennale** [comment]
Hi SDET,

Please have look, age validation block of code has been added.

Regards
Tester

**Comment by RamChennale** [comment]
Hello,

All right, everything looks good please push your all new changes to the main 'master'.
Thanks man.

**Comment by Ram-Chennale** [comment]
you are welcome, I will do it  ...!!

Thanks for appreciation.

**Pull request merged**
